# Generated by Django 4.2.17 on 2024-12-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_achievement_userachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='image',
        ),
    ]
