# Generated by Django 5.1.3 on 2025-02-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_levelhistory_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/', verbose_name='Изображение варианта'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение вопроса'),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный вариант'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст вопроса'),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название формы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание формы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='form_images/', verbose_name='Изображение формы')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.form'),
        ),
        migrations.DeleteModel(
            name='LevelHistory',
        ),
    ]
